export type Speaker = {
  id: string;
  name: string;
  role: string;
  company: string;
  country: string;
  flag: string;
  website?: string;
  bio: string;
  sessionTitle: string;
  sessionDescription: string;
  track: "art" | "facilitation" | "business" | "keynote" | "plenary";
  photo?: string;
  videoUrl?: string;
  sessionId: string;
};

const img = (id: string) => `https://lh3.googleusercontent.com/d/${id}`;

export const speakers: Speaker[] = [
  {
    id: "david-sibbet",
    name: "David Sibbet",
    role: "Founder & President Emeritus",
    company: "The Grove Consultants International",
    country: "USA",
    flag: "🇺🇸",
    website: "https://www.grove.com",
    bio: "David Sibbet is widely regarded as the father of visual facilitation. In 1977 he founded The Grove Consultants International in San Francisco and spent the next five decades pioneering the use of large-scale interactive graphics to help organisations think, align, and move forward. His clients have included Apple, Nike, Adobe, HP, and Procter & Gamble. He is the author of four landmark books: Visual Meetings, Visual Teams, Visual Leaders, and Visual Consulting, all published by John Wiley & Sons. The Organisation Development Network awarded him their Lifetime Achievement Award. He is a certified Jungian Deep Coach and is now focused on writing, mentoring, and supporting the next generation of visual practitioners.",
    sessionTitle: "Conceptual Jazz with the Group Graphics Keyboard",
    sessionDescription: "David's opening keynote introduces his new work on the Art of Process Design, exploring how visual facilitators can work more fluidly and flexibly across formats, using simpler, more interactive practices. He is particularly looking forward to connecting with practitioners who are imagining their way into a world laced with AI and virtual work.",
    track: "keynote",
    photo: img("1r3YrsgczfRG_iSsSCjky-lv29L07Ai2p"),
    videoUrl: "",
    sessionId: "wed-opening"
  },
  {
    id: "ben-crothers",
    name: "Ben Crothers",
    role: "Principal Facilitator",
    company: "Bright Pilots",
    country: "Australia",
    flag: "🇦🇺",
    website: "https://brightpilots.com",
    bio: "Ben has been on the pens for over 25 years, helping teams solve tough challenges through facilitation and visualisation. He is one of the original creators of the much-loved Atlassian Team Playbook, and the author of several books including Presto Sketching, Draw in 4, and 50 Remote-Friendly Icebreakers. He has worked with start-ups and large tech companies, government, universities, and non-profits across strategy, innovation, and decision-making.",
    sessionTitle: "Drawing Tricky Concepts More Creatively with FLARE",
    sessionDescription: "FLARE is a simple but highly effective method for drawing vague, abstract, and complex topics. In this hands-on workshop, participants will practise FLARE by drawing intangible concepts, apply it to turn clichés into clarity, and discover how to use the prompts in their facilitation practice to help teams have more insightful conversations.",
    track: "art",
    photo: img("1O_cRxO4ncc9LhiZ4_X3dwyqk4d96PX3a"),
    videoUrl: "https://youtu.be/nI_FrceQnkE",
    sessionId: "wed-flare"
  },
  {
    id: "deon-hanns",
    name: "Deon Hanns",
    role: "Visual Storyteller & Strategic Narrative Architect",
    company: "The San Scribe",
    country: "South Africa",
    flag: "🇿🇦",
    website: "https://www.thesanscribe.com",
    bio: "Deon Hanns is a Visual Storyteller and Strategic Narrative Architect, founder of The San Scribe: Visual Thinking Tools for Change-Makers. Information is a commodity, alignment is the competitive edge. Deon helps leaders and teams see the truth of their strategy in real time. Together with Jo Hobson he co-developed the Neuro Narrative Mapping system, translating the Science of Tracking and the sophisticated visual intelligence of the San ancestors into a high-performance framework for modern facilitators.",
    sessionTitle: "Neuro Narrative Mapping: The Tracker's Code",
    sessionDescription: "This session unveils the Neuro Narrative Mapping System, translating the Science of Tracking and the visual intelligence developed by the San ancestors into a framework for modern facilitators. Participants will experience how to use these tools to help individuals and teams move from problem fog to implementable clarity through drawing, metaphor, and collective intelligence. Co-presented with Jo Hobson.",
    track: "facilitation",
    photo: img("10ONbYl0dLw0gQSRPmczRjZRiteQMpjpK"),
    videoUrl: "https://youtu.be/zB26oI3hEDA",
    sessionId: "wed-nnm"
  },
  {
    id: "jo-hobson",
    name: "Jo Hobson",
    role: "Organisational Psychologist",
    company: "",
    country: "South Africa",
    flag: "🇿🇦",
    bio: "Jo Hobson is an Organisational Psychologist who enables thinking, learning, and performance in people, teams, and organisations. She offers Process and Strategy Facilitation, Workshop Design, Team Development, Leadership Coaching, Organisational Development, Diversity and Inclusion Solutions, and Visual Intelligence. She is passionate about helping people think, learn, and grow, to the benefit of themselves and their organisations. Together with Deon Hanns she co-developed the Neuro Narrative Mapping system.",
    sessionTitle: "Neuro Narrative Mapping: The Tracker's Code",
    sessionDescription: "This session unveils the Neuro Narrative Mapping System, translating the Science of Tracking and the visual intelligence developed by the San ancestors into a framework for modern facilitators. Participants will experience how to use these tools to help individuals and teams move from problem fog to implementable clarity through drawing, metaphor, and collective intelligence. Co-presented with Deon Hanns.",
    track: "facilitation",
    photo: img("1pagzcH4YXV7pT66hWCKVBqE9WBfQNMB9"),
    videoUrl: "https://youtu.be/zB26oI3hEDA",
    sessionId: "wed-nnm"
  },
  {
    id: "matthias-weitbrecht",
    name: "Matthias Weitbrecht",
    role: "Founder & CEO",
    company: "Visual Facilitators GmbH",
    country: "Germany",
    flag: "🇩🇪",
    website: "https://www.visualfacilitators.com/en/",
    bio: "Matthias Weitbrecht is a European pioneer in strategy visualization, process facilitation, and graphic recording. Since 2005 he has built Visual Facilitators GmbH into one of the market leaders in the German-speaking world and the Middle East, with a team of over 35 visual facilitators. He is the author of Co-Create! Das Visualisierungs-Buch (Wiley), and the first European Certified Master Visual Practitioner®. His work spans corporate strategy, organisational development, and leadership transformation.",
    sessionTitle: "Drawing the Line: A Privacy-First, Human-First AI Blueprint",
    sessionDescription: "As AI reshapes how organisations think and communicate, visual practitioners face new ethical questions. This session explores a framework for navigating AI integration in visual practice, putting privacy and human dignity at the centre of every decision.",
    track: "business",
    photo: img("1gs72t0MY82A5J1CL0NddOM-pZdCEinJc"),
    videoUrl: "",
    sessionId: "wed-ai-blueprint"
  },
  {
    id: "gill-cromhout",
    name: "Gill Cromhout",
    role: "Founder & Bikablo® Certified Global Trainer",
    company: "Drawn In",
    country: "South Africa",
    flag: "🇿🇦",
    website: "https://drawnin.co",
    bio: "Gill Cromhout is the founder of Drawn In (South Africa), a Bikablo® Certified Global Trainer, and Official Reseller of Neuland in South Africa. She is a skilled facilitator who creates spaces where people feel seen, valued, and able to express their thinking with clarity and confidence. She believes that the capacity to transform our world already lives within each of us, the facilitator's role is simply to bring that inherent capability to the surface.",
    sessionTitle: "Symbol Safari: Co-Creating Meaning",
    sessionDescription: "This hands-on session introduces Bikablo®'s Symbol Safari, an engaging approach that helps groups collaboratively transform abstract concepts into clear, meaningful visuals. Rather than relying on inspiration or creative talent, participants explore a structured yet playful way of inventing metaphors together. Co-presented with Maaike Borsboom.",
    track: "art",
    photo: img("1HqS2TUKCYMEf7mi28h9K3KKmJWG1GFBO"),
    videoUrl: "",
    sessionId: "wed-symbol"
  },
  {
    id: "maaike-borsboom",
    name: "Maaike Borsboom",
    role: "Founder & Bikablo® Certified Global Trainer",
    company: "INKSIGHT",
    country: "Netherlands",
    flag: "🇳🇱",
    website: "https://inksight.nl/en/",
    bio: "Maaike Borsboom is the founder of INKSIGHT (Netherlands) and a Bikablo® Certified Global Trainer. With a background as a team manager and mediator in social work, she facilitates learning processes that spark visual thinking, creativity, and meaningful dialogue. By combining Solution-Focused Dialogues with visualisation, she helps individuals and groups gain clarity by literally making their thinking visible.",
    sessionTitle: "Symbol Safari: Co-Creating Meaning",
    sessionDescription: "This hands-on session introduces Bikablo®'s Symbol Safari, an engaging approach that helps groups collaboratively transform abstract concepts into clear, meaningful visuals. Rather than relying on inspiration or creative talent, participants explore a structured yet playful way of inventing metaphors together. Co-presented with Gill Cromhout.",
    track: "art",
    photo: img("1CMOjMXlctzcSSBY9MaENk82CBgeh-PE4"),
    videoUrl: "",
    sessionId: "wed-symbol"
  },
  {
    id: "nora-sheffe",
    name: "Nora Sheffe",
    role: "President, CEO & Lead Facilitator",
    company: "Sheffe Consulting",
    country: "USA",
    flag: "🇺🇸",
    website: "https://sheffeconsulting.com",
    bio: "Nora Sheffe is an internationally accredited Master Facilitator and President of Sheffe Consulting. Over 25 years she has led more than 1,000 strategic sessions across 15 countries, guiding complex multi-stakeholder conversations toward clear, high-impact outcomes. She believes the best facilitation is not accidental, it is designed.",
    sessionTitle: "Leveraging the Facilitation & Graphic Recorder Partnership",
    sessionDescription: "When graphic recording and facilitation are treated as separate services, value is left on the table. When designed together, with scope, roles, and creative parameters clarified from the outset, something far more powerful becomes possible. This session explores what it means for facilitators and graphic recorders to operate as a true design team. Co-presented with James Durno.",
    track: "facilitation",
    photo: img("1iMS_r2zAk3cWt_kWF627x40m6k5zhLKN"),
    videoUrl: "",
    sessionId: "wed-partnership"
  },
  {
    id: "james-durno",
    name: "James Durno",
    role: "Graphic Recorder & Visual Communications Consultant",
    company: "",
    country: "South Africa",
    flag: "🇿🇦",
    bio: "James Durno is widely regarded as a pioneer of graphic recording in South Africa, with over 22 years of experience as a Visual Communications Consultant and Fine Artist. He helps organisations think visually, translating complex conversations, strategies, and ideas into engaging visual narratives in real time. His clients include Microsoft, Coca-Cola, Anglo American, Barclays, Vodacom, Discovery, Investec, Deloitte, and Wits Business School, among many others.",
    sessionTitle: "Leveraging the Facilitation & Graphic Recorder Partnership",
    sessionDescription: "When graphic recording and facilitation are treated as separate services, value is left on the table. When designed together, with scope, roles, and creative parameters clarified from the outset, something far more powerful becomes possible. This session explores what it means for facilitators and graphic recorders to operate as a true design team. Co-presented with Nora Sheffe.",
    track: "facilitation",
    photo: img("1Tbyz1tOUeJRfjW6tuPbJQelLocU2hy0f"),
    videoUrl: "",
    sessionId: "wed-partnership"
  },
  {
    id: "jim-nuttle",
    name: "Jim Nuttle",
    role: "Graphic Recorder",
    company: "Jim Nuttle, Inc.",
    country: "USA",
    flag: "🇺🇸",
    website: "https://jimnuttle.com",
    bio: "Jim Nuttle goes to meetings and draws pictures, unique images that engage people, stimulate conversation, and help everyone remember what they talked about. With decades of experience as a graphic recorder, Jim is known for his ability to capture fast-moving conversations with clarity, humour, and precision.",
    sessionTitle: "Don't Panic! A Survival Guide for Recorders",
    sessionDescription: "A hands-on workshop focused on techniques for quickly pivoting and adjusting graphic capture during a shifting conversation. Participants will learn simple and effective techniques to enhance their ability to think and draw quickly in real-time situations, including tips for handling fastballs, curveballs, and anything else thrown at them during a live session.",
    track: "business",
    photo: img("1mQgkVJxewBwCoECXBjCvMK-fXIpf1cHf"),
    videoUrl: "",
    sessionId: "wed-survival"
  },
  {
    id: "nick-walsh",
    name: "Nick Walsh",
    role: "Graphic Recorder & Creative Director",
    company: "Nick Walsh Creative",
    country: "South Africa",
    flag: "🇿🇦",
    website: "https://nickwalshcreative.com",
    bio: "Born in Zimbabwe and educated in South Africa, Nick Walsh spent 20 years in international advertising before stepping behind the camera as a commercial film and animation director. He has come full circle to where it all started, doodling. Nick is a graphic recorder with both international and South African clients, capturing the essence of conversations in real time for audiences who love watching ideas unfold before their eyes.",
    sessionTitle: "People in Motion: Drawing Characters that Speak",
    sessionDescription: "A fast-paced, interactive session that brings visual notes to life by sketching people on the move, creating emotion, exploring visual metaphors, and telling colourful, memorable stories. Participants will learn how to draw beyond stick figures, introduce gender, race, and cultural clues, and tell a simple story through positioning of text and image.",
    track: "art",
    photo: img("1B3knoneG4xmvx-nwIlRzApzPvbytCETr"),
    videoUrl: "",
    sessionId: "thu-characters"
  },
  {
    id: "axelle-vanquaillie",
    name: "Axelle Vanquaillie",
    role: "Visual Facilitator",
    company: "Visual Harvesting",
    country: "Belgium",
    flag: "🇧🇪",
    website: "https://www.visualharvesting.com",
    bio: "With over 15 years of experience, Axelle helps organisations worldwide make complex conversations visible, meaningful, and actionable. Her work goes far beyond drawing, she helps teams think, align, and make decisions through visual language. Her motto: the more challenging, the better. She has worked on Human Rights programmes in Asian factories, training facilitators to use visual tools to shift power dynamics and enable sustainable change.",
    sessionTitle: "Visual Tools to Change an Industry, Meeting by Meeting",
    sessionDescription: "This session shares insights from an international Human Rights programme in Asian factories, where visual facilitation supported dialogue between factory workers and management. Participants will explore four distinct roles a visual facilitator can play in systemic change, discovering how to equip others to carry the work forward long after you have left the room.",
    track: "facilitation",
    photo: img("18v6RlqbkQd_1qjEQAw5PBvuUHM6hUCRL"),
    videoUrl: "https://youtube.com/shorts/mtMum9PUlgM",
    sessionId: "thu-visual-tools"
  },
  {
    id: "sonia-garcia-farina",
    name: "Sonia Garcia Farina",
    role: "Human Technology Consultant",
    company: "Senet Consultores",
    country: "Spain",
    flag: "🇪🇸",
    website: "https://www.senetconsultores.com",
    bio: "Sonia leverages Visual Thinking and Strategic Gamification to transform organisational complexity into clarity, helping leaders and teams make better decisions in high-stakes environments. She believes that when people can see their thinking, they can change it.",
    sessionTitle: "The Visual Journey: Transforming Tourism Experience through Visual Thinking",
    sessionDescription: "What if the tourism industry could think more clearly, communicate more effectively, and make better decisions through visual thinking? This hands-on session travels through the tourism value chain, discovering how Visual Thinking tools can be applied at every stage, from customer experience design to team alignment to strategic planning.",
    track: "business",
    photo: img("19-TpVF0OqBbqj15Uc77bvCWu9wURbsYl"),
    videoUrl: "https://youtube.com/shorts/ikXnBPCnVSI",
    sessionId: "thu-tourism"
  },
  {
    id: "elise-white",
    name: "Elise White",
    role: "Innovation Strategist",
    company: "Reed Smith LLP",
    country: "USA",
    flag: "🇺🇸",
    website: "https://www.reedsmith.com",
    bio: "Elise White is an innovation strategist at Reed Smith LLP, helping a global law firm navigate disruption and the future of work through facilitation, visual strategy, and design thinking. Her session draws on a simple but powerful premise: the creative disciplines we pursue outside our professional work are resources waiting to be integrated.",
    sessionTitle: "Draw from Everything",
    sessionDescription: "What does oil painting have to do with graphic recording? More than you think. This workshop invites participants to surface their own creative pursuits, past or present, extract the transferable principles within them, and map those insights onto real challenges in their graphic recording or facilitation work. No two people will leave with the same takeaways, because no two people are drawing from the same well.",
    track: "facilitation",
    photo: img("1NevUjFBQ80VFsSh-WCm-cZ936Z8_NMGd"),
    videoUrl: "",
    sessionId: "thu-draw"
  },
  {
    id: "dana-rulf",
    name: "Dana Rulf",
    role: "Visual Practitioner & Founder",
    company: "speakture GmbH",
    country: "Switzerland",
    flag: "🇨🇭",
    website: "https://speakture.ch",
    bio: "Dana Rulf is the founder of speakture GmbH (\"from speaking to picture\"), a Switzerland-based business specialising in visual thinking in organisational and strategic contexts. With over 20 years of experience in international business environments and an MBA background, she helps organisations make complex topics visible, structure thinking, and create shared understanding that enables action. She is co-founder and president of Visual Practitioners Switzerland (VPS).",
    sessionTitle: "From Idea to Impact: Building a Visual Practitioners Community That Actually Works",
    sessionDescription: "Dana shares the story of founding Visual Practitioners Switzerland, from the initial idea to a growing, active community, including the challenges, tensions, and decisions that shaped its development. Rather than a polished success story, this session focuses on what actually happens behind the scenes when building a professional community in an emerging field.",
    track: "business",
    photo: img("15L7OvFrVNBiQkZm2CiUPVPCfQdHx9VhZ"),
    videoUrl: "",
    sessionId: "thu-community"
  },
  {
    id: "kati-orav",
    name: "Kati Orav",
    role: "Visual Facilitator & Educator",
    company: "Creativity Catcher",
    country: "Estonia",
    flag: "🇪🇪",
    website: "https://creativitycatcher.com",
    bio: "Kati Orav is a TEDx speaker, award-winning impact trainer, and founder of The Imperfect Line Movement. Her work is dedicated to one thing: helping people reclaim their creativity and clarity by short-circuiting perfectionism through simple, visual thinking. You do not need to be an artist. You just need a piece of paper, a pencil, and the courage to start.",
    sessionTitle: "Bringing Visual Practices into Education: Beyond a Global Framework for Teachers",
    sessionDescription: "The IFVP Institute Educators Committee is building an international framework to help teachers worldwide embed visual practices into their daily work, and this session invites participants to help shape it. This is not a presentation about a framework. It is an invitation to co-create one.",
    track: "business",
    photo: img("1OGhJxqvuax5mI3A7pNuuszXfCOIWTcut"),
    videoUrl: "",
    sessionId: "fri-education"
  },
  {
    id: "alice-edy",
    name: "Alice Edy",
    role: "Graphic Recorder & Visual Artist",
    company: "Live Drawing",
    country: "Australia",
    flag: "🇦🇺",
    website: "https://www.livedrawing.com.au",
    bio: "Originally from South Africa, Alice Edy is a graphic recorder and visual artist based in Melbourne, Australia. She holds two Masters degrees, a Master of Arts in English Literature from the University of Cape Town (verbal-visual semiotics) and a Master of Fine Arts from the Victorian College of the Arts. Her practice sits deliberately at the intersection of commercial visual communication and fine art, and she has practised as a graphic recorder for over ten years across government, corporate, and education sectors.",
    sessionTitle: "The Art of the Line: Situating Graphic Recording within the Visual Arts",
    sessionDescription: "This workshop situates graphic recording within a broader art-historical lineage of verbal-visual communication spanning tens of thousands of years, from Southern African cave art through to contemporary artists. Drawing on fine arts theory, the session asks: what kind of knowledge does a drawn line produce? Are we, as graphic recorders, scribes or artists? The session does not teach drawing technique. It reframes what drawing already is.",
    track: "art",
    photo: img("1zzz9FffJFyO1mjsQyoZPhRlPlCyATbOc"),
    videoUrl: "https://youtu.be/YLNicEpqje4",
    sessionId: "fri-situating"
  },
  {
    id: "erin-gordon",
    name: "Erin Gordon",
    role: "Founding Facilitator & Visual Strategist",
    company: "WAYFIND",
    country: "USA",
    flag: "🇺🇸",
    website: "https://thewayfind.com",
    bio: "Erin Gordon is a certified master facilitator, seasoned strategist, and coach. She works with practical, creative techniques to help groups and individuals find their way forward, not by telling them where to go, but by designing the conditions that make the path visible.",
    sessionTitle: "From Scribe to Strategic Ally: Designing Partnership in Facilitation",
    sessionDescription: "Many visual practitioners know this feeling: brought in late, positioned as support, unable to influence the design or the outcomes. It feels like a drawing problem. It isn't. It is a partnership design challenge. This session explores what shifts when we intentionally design partnership in facilitation, working with a practical framework built around Identity, Design, and Intervention.",
    track: "facilitation",
    photo: img("1LSoYAmhvE327ndcNk-VO9Spx-KgU5Ryq"),
    videoUrl: "https://youtu.be/0Z72yBHW_tk",
    sessionId: "fri-scribe"
  },
  {
    id: "jess-tenorio",
    name: "Jess Tenório",
    role: "Graphic Facilitator, Visual Thinking Educator & Author",
    company: "Jess Tenório Facilitação Gráfica",
    country: "Brazil",
    flag: "🇧🇷",
    website: "https://www.jesstenorio.com",
    bio: "Jess Tenório is a Brazilian graphic facilitator, visual thinking educator, and author based in São Paulo. Her work connects visual practice, deep listening, and participatory facilitation across corporate, educational, and community contexts. She believes that when we draw together, we make each other visible.",
    sessionTitle: "Drawing Voices: Graphic Facilitation with Traditional Peoples in Brazil",
    sessionDescription: "What happens when the facilitator puts down assumptions and picks up a marker in a community where words alone are not enough? This session shares stories from the field, real experiences of using graphic facilitation in cross-cultural and multilingual settings with traditional peoples in Brazil. Every community deserves a visual record of its own story.",
    track: "business",
    photo: img("10e4xANxPHixumTpnScM5yNFMEdfhP_oi"),
    videoUrl: "https://youtube.com/shorts/Q1SdClM9pX0",
    sessionId: "fri-brazil"
  },
  {
    id: "donatella-pastorino",
    name: "Donatella Pastorino",
    role: "Visual Practitioner",
    company: "",
    country: "",
    flag: "🌍",
    bio: "Bio coming soon.",
    sessionTitle: "Graphic Jam with Drinks",
    sessionDescription: "Co-facilitating the Wednesday evening Graphic Jam, an informal, high-energy creative session to close the first full day of the Summit.",
    track: "plenary",
    photo: "",
    videoUrl: "",
    sessionId: "wed-graphicjam"
  }
];
